# -*- coding: utf-8 -*-
"""cancer_detection_project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWxt7bsPz2rDAAXJHyXT_ULDedqF-Zj4
"""

import pandas as pd

x = pd.read_excel(r"guilherm.xlsx")

column1 = []
column2 = []
column3 = []
column4 = []
column5 = []
column6 = []
pos = []
neg = []

cont = 0
jump = 6

t = len(x["Idade"]) - 1 #number of lines

patient = {}
feat = []

while cont < t:
  column1.append(x["Idade"][cont])
  column2.append(x["Sexo"][cont])
  column3.append(x["% de blastos"][cont])
  column4.append(x["LDH (U/L)"][cont])
  column5.append(x["TP53"][cont])
  column6.append(x["CEBPA"][cont])
  feat.append(column1[cont])
  feat.append(column2[cont])
  feat.append(column3[cont])
  feat.append(column4[cont])
  feat.append(column5[cont])
  feat.append(column6[cont])
  patient["paciente[{}]".format(cont + 1)] = feat[jump - 6:jump]
  jump += 6
  cont += 1
i = 0
for data in patient.values():
  if data[2] > 0.200:
    pos.append("paciente[{}]".format(i + 1))
  else:
    neg.append("paciente[{}]".format(i + 1))
  i += 1

print("Lista de pacientes doentes:\n\n", pos)

list_pos = ""
for pat in pos:
  list_pos = list_pos + pat + ", "

print("Quantitativo de pacientes doentes:\t", len(pos))

quant_pos = 0
while quant_pos < len(pos):
  quant_pos = quant_pos + 1
quant_pos = str(quant_pos)

print("Lista de pacientes saudáveis:\n\n", neg)

list_neg = ""
for pat in neg:
  list_neg = list_neg + pat + ", "

print("Quantitativo de pacientes saudáveis:\t", len(neg))

quant_neg = 0
while quant_neg < len(neg):
  quant_neg = quant_neg + 1
quant_neg = str(quant_neg)

from google.colab import files

with open('resultado.txt', 'a') as f:
  f.write('\n\n\tResultado do Exame:')
  f.write("\n\t--------------------\n")
  f.write("\n\n\tLista de pacientes doentes: \n\n\t")
  f.write(list_pos)
  f.write("\t")
  f.write("\n\n\tQuantitativo de pacientes doentes:\t")
  f.write(quant_pos)
  f.write("\n\n\tLista de pacientes saudáveis: \n\n\t")
  f.write(list_neg)
  f.write("\t")
  f.write("\n\n\tQuantitativo de pacientes saudáveis:\t")
  f.write(quant_neg)

files.download('resultado.txt')

arch = open("resultado.txt", "r")

print(arch.read())

arch.close()